export const dbConstants = {
    GET_ALL_USERS: "GET_ALL_USERS",
    GET_ALL_SPOTS: "GET_ALL_SPOTS",
    GET_SPOTS_BY_USER: "GET_SPOTS_BY_USER",
    CREATE_SPOT: "CREATE_SPOT",
    READ_SPOT: "GET_SPOT",
    UPDATE_SPOT: "UPDATE_SPOT",
    DELETE_SPOT: "REMOVE_SPOT",
    CREATE_POST: "CREATE_POST",
    UPDATE_POST: "UPDATE_POST",
    DELETE_POST: "DELETE_POST"
}